---
name: ci_validate_action

on:
  pull_request:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint GitHub Action files
        uses: rhysd/actionlint@v1.7.12

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install action dependencies
        run: pip install -r requirements.txt
